apiVersion: v1
kind: Service
metadata:
  name: sso-http
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentConfig: sso
  sessionAffinity: None
  type: ClusterIP